 name: Build & Test Workflow

 on: 
       [pull_request]
 jobs:
   build:

     runs-on: windows-latest

     steps:
     
     - name: Checkout code
       uses: actions/checkout@v4
     
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 8.0

     - name: Restore workloads
       run: dotnet workload restore ./Software-Engineering-Group-Project/SftEngGP.csproj

     - name: Restore dependencies
       run: dotnet restore ./Software-Engineering-Group-Project/SftEngGP.csproj

     - name: Build project
       run: dotnet build ./Software-Engineering-Group-Project/SftEngGP.csproj --framework net8.0
